// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.37595
//    <NameSpace>AzureManamgentWinRT.HostedServices</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLs>True</GenerateXMLs><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace AzureManamgentWinRT.Model.HostedServices
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


   
    public partial class HostedService
    {

        private string urlField;

        private string serviceNameField;

        private HostedServiceHostedServiceProperties hostedServicePropertiesField;

        private List<HostedServiceDeployment> deploymentsField;

        private string defaultWinRmCertificateThumbprintField;

        public HostedService()
        {
            this.deploymentsField = new List<HostedServiceDeployment>();
            this.hostedServicePropertiesField = new HostedServiceHostedServiceProperties();
        }

        [XmlElement(Order = 0)]
        public string Url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }

        [XmlElement(Order = 1)]
        public string ServiceName
        {
            get
            {
                return this.serviceNameField;
            }
            set
            {
                this.serviceNameField = value;
            }
        }

        [XmlElement(Order = 2)]
        public HostedServiceHostedServiceProperties HostedServiceProperties
        {
            get
            {
                return this.hostedServicePropertiesField;
            }
            set
            {
                this.hostedServicePropertiesField = value;
            }
        }

        [XmlArray(Order = 3)]
        [XmlArrayItem("Deployment", IsNullable = false)]
        public List<HostedServiceDeployment> Deployments
        {
            get
            {
                return this.deploymentsField;
            }
            set
            {
                this.deploymentsField = value;
            }
        }

        [XmlElement(Order = 4)]
        public string DefaultWinRmCertificateThumbprint
        {
            get
            {
                return this.defaultWinRmCertificateThumbprintField;
            }
            set
            {
                this.defaultWinRmCertificateThumbprintField = value;
            }
        }
    }

   
    [XmlType(AnonymousType = true, Namespace = "http://schemas.microsoft.com/windowsazure")]
    public partial class HostedServiceHostedServiceProperties
    {

        private string descriptionField;

        private string affinityGroupField;

        private string locationField;

        private string labelField;

        private string statusField;

        private string dateCreatedField;

        private string dateLastModifiedField;

        private List<HostedServiceHostedServicePropertiesExtendedProperty> extendedPropertiesField;

        private string guestAgentTypeField;

        public HostedServiceHostedServiceProperties()
        {
            this.extendedPropertiesField = new List<HostedServiceHostedServicePropertiesExtendedProperty>();
        }

        [XmlElement(Order = 0)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        [XmlElement(Order = 1)]
        public string AffinityGroup
        {
            get
            {
                return this.affinityGroupField;
            }
            set
            {
                this.affinityGroupField = value;
            }
        }

        [XmlElement(Order = 2)]
        public string Location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }

        [XmlElement(Order = 3)]
        public string Label
        {
            get
            {
                return this.labelField;
            }
            set
            {
                this.labelField = value;
            }
        }

        [XmlElement(Order = 4)]
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        [XmlElement(Order = 5)]
        public string DateCreated
        {
            get
            {
                return this.dateCreatedField;
            }
            set
            {
                this.dateCreatedField = value;
            }
        }

        [XmlElement(Order = 6)]
        public string DateLastModified
        {
            get
            {
                return this.dateLastModifiedField;
            }
            set
            {
                this.dateLastModifiedField = value;
            }
        }

        [XmlArray(Order = 7)]
        [XmlArrayItem("ExtendedProperty", IsNullable = false)]
        public List<HostedServiceHostedServicePropertiesExtendedProperty> ExtendedProperties
        {
            get
            {
                return this.extendedPropertiesField;
            }
            set
            {
                this.extendedPropertiesField = value;
            }
        }

        [XmlElement(Order = 8)]
        public string GuestAgentType
        {
            get
            {
                return this.guestAgentTypeField;
            }
            set
            {
                this.guestAgentTypeField = value;
            }
        }
    }

   
    public partial class HostedServiceHostedServicePropertiesExtendedProperty
    {

        private string nameField;

        private string valueField;

        [XmlElement(Order = 0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        [XmlElement(Order = 1)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

  
    public partial class HostedServiceDeployment
    {

        private string nameField;

        private string deploymentSlotField;

        private string privateIDField;

        private string statusField;

        private string labelField;

        private string urlField;

        private string configurationField;

        private List<HostedServiceDeploymentRoleInstance> roleInstanceListField;

        private HostedServiceDeploymentUpgradeStatus upgradeStatusField;

        private string upgradeDomainCountField;

        private List<HostedServiceDeploymentRole> roleListField;

        private string sdkVersionField;

        private string lockedField;

        private string rollbackAllowedField;

        private string createdTimeField;

        private string lastModifiedTimeField;

        private string virtualNetworkNameField;

        private HostedServiceDeploymentDns dnsField;

        private List<HostedServiceDeploymentExtendedProperty> extendedPropertiesField;

        private HostedServiceDeploymentPersistentVMDowntime persistentVMDowntimeField;

        private List<HostedServiceDeploymentVirtualIP> virtualIPsField;

        public HostedServiceDeployment()
        {
            this.virtualIPsField = new List<HostedServiceDeploymentVirtualIP>();
            this.persistentVMDowntimeField = new HostedServiceDeploymentPersistentVMDowntime();
            this.extendedPropertiesField = new List<HostedServiceDeploymentExtendedProperty>();
            this.dnsField = new HostedServiceDeploymentDns();
            this.roleListField = new List<HostedServiceDeploymentRole>();
            this.upgradeStatusField = new HostedServiceDeploymentUpgradeStatus();
            this.roleInstanceListField = new List<HostedServiceDeploymentRoleInstance>();
        }

        [XmlElement(Order = 0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        [XmlElement(Order = 1)]
        public string DeploymentSlot
        {
            get
            {
                return this.deploymentSlotField;
            }
            set
            {
                this.deploymentSlotField = value;
            }
        }

        [XmlElement(Order = 2)]
        public string PrivateID
        {
            get
            {
                return this.privateIDField;
            }
            set
            {
                this.privateIDField = value;
            }
        }

        [XmlElement(Order = 3)]
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        [XmlElement(Order = 4)]
        public string Label
        {
            get
            {
                return this.labelField;
            }
            set
            {
                this.labelField = value;
            }
        }

        [XmlElement(Order = 5)]
        public string Url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }

        [XmlElement(Order = 6)]
        public string Configuration
        {
            get
            {
                return this.configurationField;
            }
            set
            {
                this.configurationField = value;
            }
        }

        [XmlArray(Order = 7)]
        [XmlArrayItem("RoleInstance", IsNullable = false)]
        public List<HostedServiceDeploymentRoleInstance> RoleInstanceList
        {
            get
            {
                return this.roleInstanceListField;
            }
            set
            {
                this.roleInstanceListField = value;
            }
        }

        [XmlElement(Order = 8)]
        public HostedServiceDeploymentUpgradeStatus UpgradeStatus
        {
            get
            {
                return this.upgradeStatusField;
            }
            set
            {
                this.upgradeStatusField = value;
            }
        }

        [XmlElement(Order = 9)]
        public string UpgradeDomainCount
        {
            get
            {
                return this.upgradeDomainCountField;
            }
            set
            {
                this.upgradeDomainCountField = value;
            }
        }

        [XmlArray(Order = 10)]
        [XmlArrayItem("Role", IsNullable = false)]
        public List<HostedServiceDeploymentRole> RoleList
        {
            get
            {
                return this.roleListField;
            }
            set
            {
                this.roleListField = value;
            }
        }

        [XmlElement(Order = 11)]
        public string SdkVersion
        {
            get
            {
                return this.sdkVersionField;
            }
            set
            {
                this.sdkVersionField = value;
            }
        }

        [XmlElement(Order = 12)]
        public string Locked
        {
            get
            {
                return this.lockedField;
            }
            set
            {
                this.lockedField = value;
            }
        }

        [XmlElement(Order = 13)]
        public string RollbackAllowed
        {
            get
            {
                return this.rollbackAllowedField;
            }
            set
            {
                this.rollbackAllowedField = value;
            }
        }

        [XmlElement(Order = 14)]
        public string CreatedTime
        {
            get
            {
                return this.createdTimeField;
            }
            set
            {
                this.createdTimeField = value;
            }
        }

        [XmlElement(Order = 15)]
        public string LastModifiedTime
        {
            get
            {
                return this.lastModifiedTimeField;
            }
            set
            {
                this.lastModifiedTimeField = value;
            }
        }

        [XmlElement(Order = 16)]
        public string VirtualNetworkName
        {
            get
            {
                return this.virtualNetworkNameField;
            }
            set
            {
                this.virtualNetworkNameField = value;
            }
        }

        [XmlElement(Order = 17)]
        public HostedServiceDeploymentDns Dns
        {
            get
            {
                return this.dnsField;
            }
            set
            {
                this.dnsField = value;
            }
        }

        [XmlArray(Order = 18)]
        [XmlArrayItem("ExtendedProperty", IsNullable = false)]
        public List<HostedServiceDeploymentExtendedProperty> ExtendedProperties
        {
            get
            {
                return this.extendedPropertiesField;
            }
            set
            {
                this.extendedPropertiesField = value;
            }
        }

        [XmlElement(Order = 19)]
        public HostedServiceDeploymentPersistentVMDowntime PersistentVMDowntime
        {
            get
            {
                return this.persistentVMDowntimeField;
            }
            set
            {
                this.persistentVMDowntimeField = value;
            }
        }

        [XmlArray(Order = 20)]
        [XmlArrayItem("VirtualIP", IsNullable = false)]
        public List<HostedServiceDeploymentVirtualIP> VirtualIPs
        {
            get
            {
                return this.virtualIPsField;
            }
            set
            {
                this.virtualIPsField = value;
            }
        }
    }

 
    public partial class HostedServiceDeploymentRoleInstance
    {

        private string roleNameField;

        private string instanceNameField;

        private string instanceStatusField;

        private string instanceUpgradeDomainField;

        private string instanceFaultDomainField;

        private string instanceSizeField;

        private string instanceStateDetailsField;

        private string instanceErrorCodeField;

        private string ipAddressField;

        private List<HostedServiceDeploymentRoleInstanceInstanceEndpoint> instanceEndpointsField;

        private string powerStateField;

        private string hostNameField;

        private string remoteAccessCertificateThumbprintField;

        public HostedServiceDeploymentRoleInstance()
        {
            this.instanceEndpointsField = new List<HostedServiceDeploymentRoleInstanceInstanceEndpoint>();
        }

        [XmlElement(Order = 0)]
        public string RoleName
        {
            get
            {
                return this.roleNameField;
            }
            set
            {
                this.roleNameField = value;
            }
        }

        [XmlElement(Order = 1)]
        public string InstanceName
        {
            get
            {
                return this.instanceNameField;
            }
            set
            {
                this.instanceNameField = value;
            }
        }

        [XmlElement(Order = 2)]
        public string InstanceStatus
        {
            get
            {
                return this.instanceStatusField;
            }
            set
            {
                this.instanceStatusField = value;
            }
        }

        [XmlElement(Order = 3)]
        public string InstanceUpgradeDomain
        {
            get
            {
                return this.instanceUpgradeDomainField;
            }
            set
            {
                this.instanceUpgradeDomainField = value;
            }
        }

        [XmlElement(Order = 4)]
        public string InstanceFaultDomain
        {
            get
            {
                return this.instanceFaultDomainField;
            }
            set
            {
                this.instanceFaultDomainField = value;
            }
        }

        [XmlElement(Order = 5)]
        public string InstanceSize
        {
            get
            {
                return this.instanceSizeField;
            }
            set
            {
                this.instanceSizeField = value;
            }
        }

        [XmlElement(Order = 6)]
        public string InstanceStateDetails
        {
            get
            {
                return this.instanceStateDetailsField;
            }
            set
            {
                this.instanceStateDetailsField = value;
            }
        }

        [XmlElement(Order = 7)]
        public string InstanceErrorCode
        {
            get
            {
                return this.instanceErrorCodeField;
            }
            set
            {
                this.instanceErrorCodeField = value;
            }
        }

        [XmlElement(Order = 8)]
        public string IpAddress
        {
            get
            {
                return this.ipAddressField;
            }
            set
            {
                this.ipAddressField = value;
            }
        }

        [XmlArray(Order = 9)]
        [XmlArrayItem("InstanceEndpoint", IsNullable = false)]
        public List<HostedServiceDeploymentRoleInstanceInstanceEndpoint> InstanceEndpoints
        {
            get
            {
                return this.instanceEndpointsField;
            }
            set
            {
                this.instanceEndpointsField = value;
            }
        }

        [XmlElement(Order = 10)]
        public string PowerState
        {
            get
            {
                return this.powerStateField;
            }
            set
            {
                this.powerStateField = value;
            }
        }

        [XmlElement(Order = 11)]
        public string HostName
        {
            get
            {
                return this.hostNameField;
            }
            set
            {
                this.hostNameField = value;
            }
        }

        [XmlElement(Order = 12)]
        public string RemoteAccessCertificateThumbprint
        {
            get
            {
                return this.remoteAccessCertificateThumbprintField;
            }
            set
            {
                this.remoteAccessCertificateThumbprintField = value;
            }
        }
    }

    
    public partial class HostedServiceDeploymentRoleInstanceInstanceEndpoint
    {

        private string nameField;

        private string vipField;

        private string publicPortField;

        private string localPortField;

        private string protocolField;

        [XmlElement(Order = 0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        [XmlElement(Order = 1)]
        public string Vip
        {
            get
            {
                return this.vipField;
            }
            set
            {
                this.vipField = value;
            }
        }

        [XmlElement(Order = 2)]
        public string PublicPort
        {
            get
            {
                return this.publicPortField;
            }
            set
            {
                this.publicPortField = value;
            }
        }

        [XmlElement(Order = 3)]
        public string LocalPort
        {
            get
            {
                return this.localPortField;
            }
            set
            {
                this.localPortField = value;
            }
        }

        [XmlElement(Order = 4)]
        public string Protocol
        {
            get
            {
                return this.protocolField;
            }
            set
            {
                this.protocolField = value;
            }
        }
    }

   
    public partial class HostedServiceDeploymentUpgradeStatus
    {

        private string upgradeTypeField;

        private string currentUpgradeDomainStateField;

        private string currentUpgradeDomainField;

        [XmlElement(Order = 0)]
        public string UpgradeType
        {
            get
            {
                return this.upgradeTypeField;
            }
            set
            {
                this.upgradeTypeField = value;
            }
        }

        [XmlElement(Order = 1)]
        public string CurrentUpgradeDomainState
        {
            get
            {
                return this.currentUpgradeDomainStateField;
            }
            set
            {
                this.currentUpgradeDomainStateField = value;
            }
        }

        [XmlElement(Order = 2)]
        public string CurrentUpgradeDomain
        {
            get
            {
                return this.currentUpgradeDomainField;
            }
            set
            {
                this.currentUpgradeDomainField = value;
            }
        }
    }

    
    public partial class HostedServiceDeploymentRole
    {

        private string roleNameField;

        private string oSVersionField;

        private string roleTypeField;

        private HostedServiceDeploymentRoleConfigurationSets configurationSetsField;

        private string availabilitySetNameField;

        private HostedServiceDeploymentRoleDataVirtualHardDisks dataVirtualHardDisksField;

        private HostedServiceDeploymentRoleOSVirtualHardDisk oSVirtualHardDiskField;

        private string roleSizeField;

        public HostedServiceDeploymentRole()
        {
            this.oSVirtualHardDiskField = new HostedServiceDeploymentRoleOSVirtualHardDisk();
            this.dataVirtualHardDisksField = new HostedServiceDeploymentRoleDataVirtualHardDisks();
            this.configurationSetsField = new HostedServiceDeploymentRoleConfigurationSets();
        }

        [XmlElement(Order = 0)]
        public string RoleName
        {
            get
            {
                return this.roleNameField;
            }
            set
            {
                this.roleNameField = value;
            }
        }

        [XmlElement(Order = 1)]
        public string OSVersion
        {
            get
            {
                return this.oSVersionField;
            }
            set
            {
                this.oSVersionField = value;
            }
        }

        [XmlElement(Order = 2)]
        public string RoleType
        {
            get
            {
                return this.roleTypeField;
            }
            set
            {
                this.roleTypeField = value;
            }
        }

        [XmlElement(Order = 3)]
        public HostedServiceDeploymentRoleConfigurationSets ConfigurationSets
        {
            get
            {
                return this.configurationSetsField;
            }
            set
            {
                this.configurationSetsField = value;
            }
        }

        [XmlElement(Order = 4)]
        public string AvailabilitySetName
        {
            get
            {
                return this.availabilitySetNameField;
            }
            set
            {
                this.availabilitySetNameField = value;
            }
        }

        [XmlElement(Order = 5)]
        public HostedServiceDeploymentRoleDataVirtualHardDisks DataVirtualHardDisks
        {
            get
            {
                return this.dataVirtualHardDisksField;
            }
            set
            {
                this.dataVirtualHardDisksField = value;
            }
        }

        [XmlElement(Order = 6)]
        public HostedServiceDeploymentRoleOSVirtualHardDisk OSVirtualHardDisk
        {
            get
            {
                return this.oSVirtualHardDiskField;
            }
            set
            {
                this.oSVirtualHardDiskField = value;
            }
        }

        [XmlElement(Order = 7)]
        public string RoleSize
        {
            get
            {
                return this.roleSizeField;
            }
            set
            {
                this.roleSizeField = value;
            }
        }
    }

   
    [XmlType(AnonymousType = true, Namespace = "http://schemas.microsoft.com/windowsazure")]
    public partial class HostedServiceDeploymentRoleConfigurationSets
    {

        private HostedServiceDeploymentRoleConfigurationSetsConfigurationSet configurationSetField;

        public HostedServiceDeploymentRoleConfigurationSets()
        {
            this.configurationSetField = new HostedServiceDeploymentRoleConfigurationSetsConfigurationSet();
        }

        [XmlElement(Order = 0)]
        public HostedServiceDeploymentRoleConfigurationSetsConfigurationSet ConfigurationSet
        {
            get
            {
                return this.configurationSetField;
            }
            set
            {
                this.configurationSetField = value;
            }
        }
    }

   
    [XmlType(AnonymousType = true, Namespace = "http://schemas.microsoft.com/windowsazure")]
    public partial class HostedServiceDeploymentRoleConfigurationSetsConfigurationSet
    {

        private string configurationSetTypeField;

        private HostedServiceDeploymentRoleConfigurationSetsConfigurationSetInputEndpoints inputEndpointsField;

        private HostedServiceDeploymentRoleConfigurationSetsConfigurationSetSubnetNames subnetNamesField;

        public HostedServiceDeploymentRoleConfigurationSetsConfigurationSet()
        {
            this.subnetNamesField = new HostedServiceDeploymentRoleConfigurationSetsConfigurationSetSubnetNames();
            this.inputEndpointsField = new HostedServiceDeploymentRoleConfigurationSetsConfigurationSetInputEndpoints();
        }

        [XmlElement(Order = 0)]
        public string ConfigurationSetType
        {
            get
            {
                return this.configurationSetTypeField;
            }
            set
            {
                this.configurationSetTypeField = value;
            }
        }

        [XmlElement(Order = 1)]
        public HostedServiceDeploymentRoleConfigurationSetsConfigurationSetInputEndpoints InputEndpoints
        {
            get
            {
                return this.inputEndpointsField;
            }
            set
            {
                this.inputEndpointsField = value;
            }
        }

        [XmlElement(Order = 2)]
        public HostedServiceDeploymentRoleConfigurationSetsConfigurationSetSubnetNames SubnetNames
        {
            get
            {
                return this.subnetNamesField;
            }
            set
            {
                this.subnetNamesField = value;
            }
        }
    }

  
    public partial class HostedServiceDeploymentRoleConfigurationSetsConfigurationSetInputEndpoints
    {

        private HostedServiceDeploymentRoleConfigurationSetsConfigurationSetInputEndpointsInputEndpoint inputEndpointField;

        public HostedServiceDeploymentRoleConfigurationSetsConfigurationSetInputEndpoints()
        {
            this.inputEndpointField = new HostedServiceDeploymentRoleConfigurationSetsConfigurationSetInputEndpointsInputEndpoint();
        }

        [XmlElement(Order = 0)]
        public HostedServiceDeploymentRoleConfigurationSetsConfigurationSetInputEndpointsInputEndpoint InputEndpoint
        {
            get
            {
                return this.inputEndpointField;
            }
            set
            {
                this.inputEndpointField = value;
            }
        }
    }

    public partial class HostedServiceDeploymentRoleConfigurationSetsConfigurationSetInputEndpointsInputEndpoint
    {

        private string loadBalancedEndpointSetNameField;

        private string localPortField;

        private string nameField;

        private string portField;

        private HostedServiceDeploymentRoleConfigurationSetsConfigurationSetInputEndpointsInputEndpointLoadBalancerProbe loadBalancerProbeField;

        private string protocolField;

        private string vipField;

        public HostedServiceDeploymentRoleConfigurationSetsConfigurationSetInputEndpointsInputEndpoint()
        {
            this.loadBalancerProbeField = new HostedServiceDeploymentRoleConfigurationSetsConfigurationSetInputEndpointsInputEndpointLoadBalancerProbe();
        }

        [XmlElement(Order = 0)]
        public string LoadBalancedEndpointSetName
        {
            get
            {
                return this.loadBalancedEndpointSetNameField;
            }
            set
            {
                this.loadBalancedEndpointSetNameField = value;
            }
        }

        [XmlElement(Order = 1)]
        public string LocalPort
        {
            get
            {
                return this.localPortField;
            }
            set
            {
                this.localPortField = value;
            }
        }

        [XmlElement(Order = 2)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        [XmlElement(Order = 3)]
        public string Port
        {
            get
            {
                return this.portField;
            }
            set
            {
                this.portField = value;
            }
        }

        [XmlElement(Order = 4)]
        public HostedServiceDeploymentRoleConfigurationSetsConfigurationSetInputEndpointsInputEndpointLoadBalancerProbe LoadBalancerProbe
        {
            get
            {
                return this.loadBalancerProbeField;
            }
            set
            {
                this.loadBalancerProbeField = value;
            }
        }

        [XmlElement(Order = 5)]
        public string Protocol
        {
            get
            {
                return this.protocolField;
            }
            set
            {
                this.protocolField = value;
            }
        }

        [XmlElement(Order = 6)]
        public string Vip
        {
            get
            {
                return this.vipField;
            }
            set
            {
                this.vipField = value;
            }
        }
    }

    public partial class HostedServiceDeploymentRoleConfigurationSetsConfigurationSetInputEndpointsInputEndpointLoadBalancerProbe
    {

        private string pathField;

        private string portField;

        private string protocolField;

        [XmlElement(Order = 0)]
        public string Path
        {
            get
            {
                return this.pathField;
            }
            set
            {
                this.pathField = value;
            }
        }

        [XmlElement(Order = 1)]
        public string Port
        {
            get
            {
                return this.portField;
            }
            set
            {
                this.portField = value;
            }
        }

        [XmlElement(Order = 2)]
        public string Protocol
        {
            get
            {
                return this.protocolField;
            }
            set
            {
                this.protocolField = value;
            }
        }
    }

    
    public partial class HostedServiceDeploymentRoleConfigurationSetsConfigurationSetSubnetNames
    {

        private string subnetNameField;

        [XmlElement(Order = 0)]
        public string SubnetName
        {
            get
            {
                return this.subnetNameField;
            }
            set
            {
                this.subnetNameField = value;
            }
        }
    }

   
    public partial class HostedServiceDeploymentRoleDataVirtualHardDisks
    {

        private HostedServiceDeploymentRoleDataVirtualHardDisksDataVirtualHardDisk dataVirtualHardDiskField;

        public HostedServiceDeploymentRoleDataVirtualHardDisks()
        {
            this.dataVirtualHardDiskField = new HostedServiceDeploymentRoleDataVirtualHardDisksDataVirtualHardDisk();
        }

        [XmlElement(Order = 0)]
        public HostedServiceDeploymentRoleDataVirtualHardDisksDataVirtualHardDisk DataVirtualHardDisk
        {
            get
            {
                return this.dataVirtualHardDiskField;
            }
            set
            {
                this.dataVirtualHardDiskField = value;
            }
        }
    }

   
    public partial class HostedServiceDeploymentRoleDataVirtualHardDisksDataVirtualHardDisk
    {

        private string hostCachingField;

        private string diskNameField;

        private string lunField;

        private string logicalDiskSizeInGBField;

        private string mediaLinkField;

        [XmlElement(Order = 0)]
        public string HostCaching
        {
            get
            {
                return this.hostCachingField;
            }
            set
            {
                this.hostCachingField = value;
            }
        }

        [XmlElement(Order = 1)]
        public string DiskName
        {
            get
            {
                return this.diskNameField;
            }
            set
            {
                this.diskNameField = value;
            }
        }

        [XmlElement(Order = 2)]
        public string Lun
        {
            get
            {
                return this.lunField;
            }
            set
            {
                this.lunField = value;
            }
        }

        [XmlElement(Order = 3)]
        public string LogicalDiskSizeInGB
        {
            get
            {
                return this.logicalDiskSizeInGBField;
            }
            set
            {
                this.logicalDiskSizeInGBField = value;
            }
        }

        [XmlElement(Order = 4)]
        public string MediaLink
        {
            get
            {
                return this.mediaLinkField;
            }
            set
            {
                this.mediaLinkField = value;
            }
        }
    }

   
    public partial class HostedServiceDeploymentRoleOSVirtualHardDisk
    {

        private string hostCachingField;

        private string diskNameField;

        private string mediaLinkField;

        private string sourceImageNameField;

        private string osField;

        [XmlElement(Order = 0)]
        public string HostCaching
        {
            get
            {
                return this.hostCachingField;
            }
            set
            {
                this.hostCachingField = value;
            }
        }

        [XmlElement(Order = 1)]
        public string DiskName
        {
            get
            {
                return this.diskNameField;
            }
            set
            {
                this.diskNameField = value;
            }
        }

        [XmlElement(Order = 2)]
        public string MediaLink
        {
            get
            {
                return this.mediaLinkField;
            }
            set
            {
                this.mediaLinkField = value;
            }
        }

        [XmlElement(Order = 3)]
        public string SourceImageName
        {
            get
            {
                return this.sourceImageNameField;
            }
            set
            {
                this.sourceImageNameField = value;
            }
        }

        [XmlElement(Order = 4)]
        public string OS
        {
            get
            {
                return this.osField;
            }
            set
            {
                this.osField = value;
            }
        }
    }

   
    public partial class HostedServiceDeploymentDns
    {

        private List<HostedServiceDeploymentDnsDnsServer> dnsServersField;

        public HostedServiceDeploymentDns()
        {
            this.dnsServersField = new List<HostedServiceDeploymentDnsDnsServer>();
        }

        [XmlArray(Order = 0)]
        [XmlArrayItem("DnsServer", IsNullable = false)]
        public List<HostedServiceDeploymentDnsDnsServer> DnsServers
        {
            get
            {
                return this.dnsServersField;
            }
            set
            {
                this.dnsServersField = value;
            }
        }
    }

   
    public partial class HostedServiceDeploymentDnsDnsServer
    {

        private string nameField;

        private string addressField;

        [XmlElement(Order = 0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        [XmlElement(Order = 1)]
        public string Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
    }

  
    public partial class HostedServiceDeploymentExtendedProperty
    {

        private string nameField;

        private string valueField;

        [XmlElement(Order = 0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        [XmlElement(Order = 1)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

   
    public partial class HostedServiceDeploymentPersistentVMDowntime
    {

        private string startTimeField;

        private string endTimeField;

        private string statusField;

        [XmlElement(Order = 0)]
        public string StartTime
        {
            get
            {
                return this.startTimeField;
            }
            set
            {
                this.startTimeField = value;
            }
        }

        [XmlElement(Order = 1)]
        public string EndTime
        {
            get
            {
                return this.endTimeField;
            }
            set
            {
                this.endTimeField = value;
            }
        }

        [XmlElement(Order = 2)]
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }

    
    public partial class HostedServiceDeploymentVirtualIP
    {

        private string addressField;

        [XmlElement(Order = 0)]
        public string Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
    }
}
