using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AzureManamgentWinRT.Model.CloudServices
{
    /// <summary>
    /// Specifies the current status of a 
    /// role instance.
    /// </summary>
    public enum HostedServiceRoleInstanceStatus
    {
        /// <summary>
        /// Indicates that the state of 
        /// the role is currently unknown.
        /// </summary>
        RoleStateUnknown,
        /// <summary>
        /// Indicates that resources
        /// are being created for a vritual
        /// machine.
        /// </summary>
        CreatingVM,
        /// <summary>
        /// Indicates that the role
        /// instance is starting.
        /// </summary>
        StartingVM,
        /// <summary>
        /// Indicates that resources are being created
        /// for a Role Instance.
        /// </summary>
        CreatingRole,
        /// <summary>
        /// Indicates that a role instance is starting.
        /// </summary>
        StartingRole,
        /// <summary>
        /// Indicates that a role instance has started
        /// and is ready to be used.
        /// </summary>
        ReadyRole,
        /// <summary>
        /// Indicates that a role instance is unavailabe
        /// for requests. This state is usually generated while the role is 
        /// being created or stopped.
        /// </summary>
        BusyRole,
        /// <summary>
        /// Indicates that a role instance is topping.
        /// </summary>
        StoppingRole,
        /// <summary>
        /// Indicates that a Virtual Machine is stopping.
        /// </summary>
        StoppingVM,
        /// <summary>
        /// Indicates that a Virtual Machine is stopping.
        /// </summary>
        DeletingVM,
        /// <summary>
        /// Indicates that a Virtual Machine is not running.
        /// This is the final state of the shutdown process, and 
        /// no other status messages should be received after 
        /// StoppedVM.
        /// </summary>
        StoppedVM,
        /// <summary>
        /// Indicates that role instance has been unexpected
        /// stopped or has failed to start.
        /// This status indcates that there is a problem this the role instance
        /// that is causing it to crash or preventing it from
        /// starting and must be corrected before the role instance
        /// can be started. The InstanceStateDetail and InstanceErrorCode
        /// fields can hold informations about this state.
        /// </summary>
        RestartingRole,
        /// <summary>
        /// Indicates that the role instance is not starting
        /// correctly. This status indicates that hter is a problem
        /// with the role instance that prevents it from starting an my be genereated
        /// after the StartingRole status or the ReadyRole status is received. The problem
        /// in the role instance must be found and corrected before the role can be 
        /// started.
        /// The InstanceStateDetail and InstanceError code fileds can hold informations
        /// about the role error that caused the state.
        /// </summary>
        CyclingRole,
        /// <summary>
        /// Indicates that a role instance has failed to start.
        /// This status indicates that ther is a problem
        /// with the role instance that prevents it from starting
        /// , and may be generated after the process returns StartingRole.
        /// The problem in the role must be found and corrected before the role can be
        /// started. The InstanceStateDetail and InstanceErrorCode filed can hold informations
        /// about the role error that caused this state, which may be useful for identifiying and debugging
        /// the problem.
        /// </summary>
        FailedStartingRole,
        /// <summary>
        /// Indicates that a Vritaul Machine has continually failed to start.
        /// This status generated by Windows Azure, and does not indicate an error with
        /// the role instance. It may be generated after the 
        /// StartingRole stae.
        /// </summary>
        FailedStaringVM,
        /// <summary>
        /// Indicates that a role instance has timed out
        /// before receiving a status message and is not responding
        /// to requests.
        /// </summary>
        UnresponsiveRole,
        /// <summary>
        /// Indicates that a role instance hase been stopped
        /// and all allocated resources have been released. This stops billing for the
        /// role instance. Role instances that have a status of StoppedDeallocated are 
        /// only returned in the role instance list, if the verions is 2013-06-01 or
        /// higher. If all role instances in the deplyoment have status of StoppedDeallocated
        /// the deployment is not returned.
        /// </summary>
        StoppedDeallocated


    }
}
